revert: "chore: remove unused frontend packages (#1785)"
This reverts commit 9e262ff4cd0030d31a29d944646753882ecc3fd9.

I don't know how this passed CI, but it fails locally with:

```
🐚 ~/dev/ftl $ git clean -fdx frontend                                                                                                        main
Removing frontend/dist/
juRemoving frontend/node_modules/
🐚 ~/dev/ftl $ just build-protos                                                                                                              main
cd frontend && npm install
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated json-schema-ref-parser@6.1.0: Please switch to @apidevtools/json-schema-ref-parser

added 648 packages, and audited 649 packages in 2s

173 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
cd backend/protos && buf generate
Failure: plugin connect-es: could not find protoc plugin for name connect-es - please make sure protoc-gen-connect-es is installed and present on your $PATH
error: Recipe `build-protos` failed on line 110 with exit code 1
```