revert: "fix: add a build.lock file to gate the buildengine (#1670)" (#1732)
This reverts commit e711523cabbc597ea7acaf0434c9e89106adb263.

```
=== Failed
=== FAIL: buildengine TestDissallowMultipleEngines (0.00s)
    /home/runner/work/ftl/ftl/buildengine/engine_test.go:65: Did not expect an error but got:
        failed to lock file at: /home/runner/.ftl/build.lock

DONE 383 tests, 1 skipped, 1 failure in 115.533s
Error: === RUN   TestDissallowMultipleEngines
    buildengine/engine_test.go:65: Did not expect an error but got:
        failed to lock file at: /home/runner/.ftl/build.lock
```

cc @safeer